### ISSUE TITLE
Eager loading not working

### ISSUE THREAD

**Issue by ekarious** [ahmerb/typescript-sequelize-example#5]
Hello,

When trying to use eager loading like this:
```
app.get('/users', (req: Request, res: Response) => {
  db.User.findAll({
    include: [{
      model: db.Post
    }]
  })
    .then((users: UserInstance[]) => res.status(200).json({ users }))
    .catch(err => res.status(500).json({ err: ['oops', err] }));
});
```
by adding include, like shown in sequelize docs.

I got a `SequelizeEagerLoadingError`.

I do not know how to fix this for now. 
Can someone replicate this ?
Thank you.

**Comment by ekarious** [comment]
Sorry, i finally could get the full error message and I forgot to use the alias.

**Comment by ahmerb** [comment]
Glad you fixed it!
